### ISSUE TITLE
Flutter web

### ISSUE THREAD

**Issue by jeansebastienZ** [luis901101/cloudinary-sdk#2]
Hello , 

How do you use it on flutter web . Dart io neither path is available on flutter web .
Could you help please ?

**Comment by luis901101** [comment]
Yep, currently the upload depends on filePath and `MultipartFile.fromFile(filePath)` which depends on `dart:io`... I have to improve that to support uploading from bytes.

**Comment by jeansebastienZ** [comment]
How much time would you need to implement it as my customer asking for this solution , i can tip you if necessary .

Regards,

**Comment by luis901101** [comment]
Done, in this commit [a139f67](https://github.com/luis901101/cloudinary-sdk/commit/a139f67091ce914ea1a3dd36cf1ed1b86e380a30) I added support for uploading a file as byte array... I also changed some things in the uploadFile(...) function params so a breaking was necessary... I currently pushed a [v2.0.0+5](https://pub.dev/packages/cloudinary_sdk) to pub.dev
