### ISSUE TITLE
how do i add a progress  status   when the file is uploading

### ISSUE THREAD

**Issue by Isaacn123** [luis901101/cloudinary-sdk#5]
onProgress: (count, total) { },

**Comment by luis901101** [comment]
This is not currently available… this feature has to be implemented.
I will take it into account for the next version.

**Comment by Isaacn123** [comment]
oh ok thanks your package is really awesome to use.. please am waiting for that feature i don't want to use another package in my app.. this one is good 
am really in need of that

**Comment by luis901101** [comment]
This was added in latest version [v4.0.1+9](https://pub.dev/packages/cloudinary_sdk/versions/4.0.1+9)
