### ISSUE TITLE
am unable to upload file progress stops at  1.0

### ISSUE THREAD

**Issue by Isaacn123** [luis901101/cloudinary-sdk#6]
Uploading image from file with progress: 1.0
I/flutter (  485): Exception occurred: DioError [DioErrorType.response]: Http status error [401]
I/flutter (  485): Source stack:
I/flutter (  485): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (  485): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (  485): #2      DioMixin.post (package:dio/src/dio_mixin.dart:97:12)
I/flutter (  485): #3      CloudinaryApi.post (package:cloudinary_sdk/src/data/cloudinary_api.dart:32:12)
I/flutter (  485): #4      CloudinaryClient.upload (package:cloudinary_sdk/src/data/cloudinary_client.dart:81:24)

**Comment by luis901101** [comment]
> Http status error [401]
That is an unauthorized request.
Check your cloudinary credentials

**Comment by Isaacn123** [comment]
thanks for the response i managed to sort it for some reason it upload after i reconfigured my keys... this is solved
